# System utilities
SYSTEM_UTILS=(
  fastfetch
  discord
  bluedevil
  bluez
  bluez-utils
  man-db
  man-pages
  gwenview
  partitionmanager
  openssh
  wget
  xdg-utils
  htop
  smartmontools
)

# Development tools
DEV_TOOLS=(
  neovim
  starship
  ghostty
  zsh
  fzf
  tmux
  rofi
  yazi
)

# System maintenance
MAINTENANCE=(
  pacman-contrib
  ufw
)

# Media packages
MEDIA=(
  vlc
  spectacle
  gimp
  spotify-launcher
)

# Fonts
FONTS=(
  ttf-nerd-fonts-symbols-mono
  ttf-nerd-fonts-symbols
  ttf-jetbrains-mono-nerd
)

# AUR packages
AUR_PACKAGES=(
  visual-studio-code-bin
  google-chrome
)

# Services to enable
SERVICES=(
  bluetooth.service
  ufw.service
)