# System utilities
SYSTEM_UTILS=(
  fastfetch
  discord
  bluedevil
  bluez
  bluez-utils
  man-db
  man-pages
  gwenview
  partitionmanager
  openssh
  wget
  xdg-utils
  htop
  smartmontools
)

# Development tools
DEV_TOOLS=(
  neovim
  starship
  ghostty
  zsh
  fzf
  tmux
  rofi
)

# System maintenance
MAINTENANCE=(
  pacman-contrib
  ufw
)

# Media packages
MEDIA=(
  vlc
  spectacle
  gimp
  spotify-launcher
)

# Fonts
FONTS=(
  ttf-nerd-fonts-symbols-mono
  ttf-nerd-fonts-symbols
)

# AUR packages
AUR_PACKAGES=(
  nerd-fonts-jetbrains-mono
  visual-studio-code-bin
  google-chrome
)

# Services to enable
SERVICES=(
  bluetooth.service
  ufw.service
)